"use client";

import React, { useEffect, useState } from "react";
import { CommunityMemberItem, User } from "@/types";
import { Crown, Shield, UserPlus, Users } from "lucide-react";

export default function CommunityRoster({ groupId, currentUser, onShowToast }: { groupId: number; currentUser: User | null; onShowToast: (message: string, points?: number, error?: boolean) => void }) {
  const [members, setMembers] = useState<CommunityMemberItem[]>([]); const [isMember, setIsMember] = useState(false); const [canModerate, setCanModerate] = useState(false); const [open, setOpen] = useState(false);
  const load = async () => { try { const res = await fetch(`/api/community?groupId=${groupId}`); const data = await res.json(); if (data.success) { setMembers(data.members); setIsMember(data.isMember); setCanModerate(data.canModerate); } } catch {} };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [groupId]);
  const action = async (actionName: string, body: Record<string, unknown> = {}) => { if (!currentUser) return onShowToast("Sign in to join a community.", undefined, true); const res = await fetch("/api/community", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: actionName, groupId, ...body }) }); const data = await res.json(); if (data.success) void load(); else onShowToast(data.error || "Community update failed.", undefined, true); };
  return <div className="border-t border-slate-800 pt-3"><div className="flex items-center justify-between"><button onClick={() => setOpen((value) => !value)} className="flex items-center gap-1.5 text-xs font-black text-slate-300"><Users className="h-3.5 w-3.5 text-indigo-400" /> {members.length} members · {members.filter((member) => member.role === "moderator").length} moderators</button>{isMember ? <button onClick={() => action("leave")} className="text-[10px] font-bold text-slate-500 hover:text-rose-300">Leave</button> : <button onClick={() => action("join")} className="inline-flex items-center gap-1 rounded-lg bg-indigo-600 px-2.5 py-1 text-[10px] font-black text-white"><UserPlus className="h-3 w-3" /> Join</button>}</div>{open && <div className="mt-3 max-h-40 space-y-1 overflow-y-auto rounded-xl bg-slate-950/70 p-2 custom-scrollbar">{members.map((member) => <div key={member.id} className="flex items-center gap-2 rounded-lg p-1.5"><img src={member.user.avatarUrl || `https://api.dicebear.com/7.x/avataaars/svg?seed=${member.user.username}`} alt="" className="h-6 w-6 rounded-full" /><span className="min-w-0 flex-1 truncate text-[11px] font-bold text-slate-200">{member.user.name}</span>{member.role === "moderator" && <span className="inline-flex items-center gap-1 text-[9px] font-black text-amber-300"><Crown className="h-3 w-3" /> MOD</span>}{canModerate && member.userId !== currentUser?.id && <button onClick={() => action("set_role", { userId: member.userId, role: member.role === "moderator" ? "member" : "moderator" })} className="text-[9px] text-indigo-300 hover:text-white">{member.role === "moderator" ? "Demote" : "Make mod"}</button>}</div>)}</div>}</div>;
}
